-- Migration: Add unique constraint to prevent duplicate submissions
-- Date: January 8, 2026
-- Issue: Duplicate submissions created from single submit attempt
-- Fix: Add unique constraint on submission_hash column

-- Add unique constraint
ALTER TABLE contributions 
ADD CONSTRAINT IF NOT EXISTS unique_submission_hash 
UNIQUE (submission_hash);

-- Add comment explaining the constraint
COMMENT ON CONSTRAINT unique_submission_hash ON contributions 
IS 'Prevents duplicate submissions by ensuring submission_hash is unique. Each submission must have a unique hash generated by crypto.randomBytes(32).toString("hex")';

-- Create index for performance (if not already created by constraint)
CREATE INDEX IF NOT EXISTS idx_contributions_submission_hash 
ON contributions(submission_hash);

-- Verify constraint was added
SELECT 
  tc.constraint_name, 
  tc.constraint_type,
  tc.table_name,
  kcu.column_name,
  pg_get_constraintdef(c.oid) as constraint_definition
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
  ON tc.constraint_name = kcu.constraint_name
JOIN pg_constraint c 
  ON c.conname = tc.constraint_name
WHERE tc.table_name = 'contributions' 
  AND tc.constraint_type = 'UNIQUE'
  AND kcu.column_name = 'submission_hash';

